In [2]:
import pandas as pd   
import pandas_gbq as pgbq 
import os
import re
import sys

In [3]:
path_note = os.getcwd()
path_src = re.sub(r'(.)notebooks','',path_note)
sys.path.append(os.path.abspath(f'{path_src}/'))

In [4]:
def get_file_local(sql):

    # substituido ler aruqivo local, nao gera o arquivo, ler no storage
    path_ = os.getcwd()
    scrp_path = f'{path_}/sql/{sql}'

    ## arquivo sql dentro da esrutura airflow: 
    f = open(scrp_path, 'r')

    conteudo = f.readlines()
    # initialize an empty string
    strsql = ""

    # converte arquivo em string
    for ln in conteudo:
        strsql += ln   

    return strsql

In [5]:
import google.auth

user = os.getlogin()
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = '/home/andre/.ssh/my-chave-gcp-devsamelo2.json'

#credencial = service_account.Credentials.from_service_account_file(key)
credencial, pid = google.auth.default(     
    scopes=[
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/bigquery",
    "https://www.googleapis.com/auth/cloud-platform"
])

In [6]:
from mygcpjobfinfam import my_execute_job
sql = get_file_local('create_information_executor_jobs.sql')
my_execute_job(sql)

Started job: custo_domestico_db94ecbb-0629-4cce-be96-cb6754414073

QueryJob<project=devsamelo2, location=US, id=custo_domestico_db94ecbb-0629-4cce-be96-cb6754414073>

In [7]:
import time
wait_time = 10
time.sleep(wait_time)

In [8]:
#substituir metodo busca sql local: '/home/airflow/dags/transporte/scripts'
strsql = 'select * from dev_monitoria.information_executor_jobs_finance'
# strsql = geraScriptSql(f'{path}/query_cust/QUERY_ANALISE_CUSTO_TABELAS.sql',None,None) #,value[1])
#GERAR DATAFRAME
df = pgbq.read_gbq(strsql, project_id='devsamelo2' , credentials=credencial, progress_bar_type=None)

In [9]:
df

,statement_type,user_email,job_id,job_type,start_time,query,state,total_bytes_billed,total_slot_ms,transferred_bytes,...,project_id,dataset_id,table_id,dataset,dataset_others,executor_anon_job,executor_parent_cons_prog_job,executor_parent_airflow_job,executor_job,dataset_id_job
0,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_59843b86-e621-414a-b595-00a791...,QUERY,2023-07-07 10:43:22.253,/*alterado a forma de agrupamento por data par...,DONE,31457280,17856,0,...,devsamelo2,dev_domestico,credito_mes,None,None,None,None,None,manual,dev_domestico
1,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_d310bd2f-ffcf-4afa-844c-880e94...,QUERY,2023-07-07 10:44:08.407,/*alterado a forma de agrupamento por data par...,DONE,31457280,18507,0,...,devsamelo2,dev_domestico,credito_mes,None,None,None,None,None,manual,dev_domestico
2,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_13bca8d7-ab95-473a-9470-7f97ff...,QUERY,2023-07-07 10:14:56.975,/*alterado a forma de agrupamento por data par...,DONE,31457280,22794,0,...,devsamelo2,dev_domestico,credito_mes,None,None,None,None,None,manual,dev_domestico
3,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_a7aa22d3-6558-4e5a-a36e-36fa37...,QUERY,2023-07-07 08:55:50.946,/*alterado a forma de agrupamento por data par...,DONE,31457280,37130,0,...,devsamelo2,dev_domestico,credito_mes,None,None,None,None,None,manual,dev_domestico
4,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,script_job_a6216e1cdfaf18c67e2e796636a50294_3,QUERY,2023-07-07 10:43:32.005,create or replace table devsamelo2.dev_domesti...,DONE,31457280,9601268,0,...,devsamelo2,dev_domestico,saldo_mes_2022,None,None,None,None,None,script_job,dev_domestico
5,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,script_job_9fb0ea1c91053efc3b7e45db9c4fa989_3,QUERY,2023-07-07 10:15:10.885,create or replace table devsamelo2.dev_domesti...,DONE,31457280,16207906,0,...,devsamelo2,dev_domestico,saldo_mes_2022,None,None,None,None,None,script_job,dev_domestico
6,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,script_job_040a7675ebf35d3992a5495f0d1c6d25_3,QUERY,2023-07-07 08:56:07.647,create or replace table devsamelo2.dev_domesti...,DONE,31457280,13047391,0,...,devsamelo2,dev_domestico,saldo_mes_2022,None,None,None,None,None,script_job,dev_domestico
7,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,script_job_393cf5a0c8744adde800d37f63ca0e40_3,QUERY,2023-07-07 10:44:18.142,create or replace table devsamelo2.dev_domesti...,DONE,31457280,10723129,0,...,devsamelo2,dev_domestico,saldo_mes_2022,None,None,None,None,None,script_job,dev_domestico
8,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_01984829-2feb-41d5-9a9f-62cc8e...,QUERY,2023-07-07 10:15:05.117,create or replace table devsamelo2.dev_domesti...,DONE,31457280,18577,0,...,devsamelo2,dev_domestico,custo_vida_2022,None,None,None,None,None,manual,dev_domestico
9,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_a94cdb1b-ab7e-44fc-b18b-98b595...,QUERY,2023-07-07 08:55:59.347,create or replace table devsamelo2.dev_domesti...,DONE,31457280,28472,0,...,devsamelo2,dev_domestico,custo_vida_2022,None,None,None,None,None,manual,dev_domestico
10,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_7e6c2cac-04ca-4ea1-83ac-8a8fd5...,QUERY,2023-07-07 10:44:11.154,create or replace table devsamelo2.dev_domesti...,DONE,31457280,19128,0,...,devsamelo2,dev_domestico,custo_vida_2022,None,None,None,None,None,manual,dev_domestico
11,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_ccbf5f67-acb0-4769-9803-ba69ae...,QUERY,2023-07-07 10:43:25.081,create or replace table devsamelo2.dev_domesti...,DONE,31457280,34165,0,...,devsamelo2,dev_domestico,custo_vida_2022,None,None,None,None,None,manual,dev_domestico
12,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_01a31931-3618-474c-8291-f35043...,QUERY,2023-07-07 10:44:07.502,/**CUSTO DE FEV: PIX TRANSF ESPACO 21/02\n TEM...,DONE,41943040,26356,0,...,devsamelo2,dev_domestico,custo_consolidado_2022,None,None,None,None,None,manual,dev_domestico
13,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_56a79ccb-7d22-4a68-953e-ed3d33...,QUERY,2023-07-07 10:43:21.308,/**CUSTO DE FEV: PIX TRANSF ESPACO 21/02\n TEM...,DONE,41943040,30809,0,...,devsamelo2,dev_domestico,custo_consolidado_2022,None,None,None,None,None,manual,dev_domestico
14,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_ef603447-5241-4243-aee3-ede8c4...,QUERY,2023-07-07 08:55:48.090,/**CUSTO DE FEV: PIX TRANSF ESPACO 21/02\n TEM...,DONE,41943040,44759,0,...,devsamelo2,dev_domestico,custo_consolidado_2022,None,None,None,None,None,manual,dev_domestico
15,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_40b8bb6d-51d3-4c3c-a1b2-e60758...,QUERY,2023-07-07 10:14:54.137,/**CUSTO DE FEV: PIX TRANSF ESPACO 21/02\n TEM...,DONE,41943040,32729,0,...,devsamelo2,dev_domestico,custo_consolidado_2022,None,None,None,None,None,manual,dev_domestico
16,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_cdd2646d-30d3-41b5-966f-6f071e...,QUERY,2023-07-07 10:44:09.374,create or replace table devsamelo2.dev_domesti...,DONE,41943040,66713,0,...,devsamelo2,dev_domestico,recebimento_geral_2022,None,None,None,None,None,manual,dev_domestico
17,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_c9df0f8f-d4d4-4bf9-8258-042e11...,QUERY,2023-07-07 08:55:53.678,create or replace table devsamelo2.dev_domesti...,DONE,41943040,83690,0,...,devsamelo2,dev_domestico,recebimento_geral_2022,None,None,None,None,None,manual,dev_domestico
18,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_aae168f0-f9c4-4db0-a4a7-6af5f6...,QUERY,2023-07-07 10:43:23.390,create or replace table devsamelo2.dev_domesti...,DONE,41943040,55919,0,...,devsamelo2,dev_domestico,recebimento_geral_2022,None,None,None,None,None,manual,dev_domestico
19,CREATE_TABLE_AS_SELECT,devsamelo-dev@devsamelo2.iam.gserviceaccount.com,custo_domestico_38058f45-a859-4c88-a58b-8190e6...,QUERY,2023-07-07 10:14:59.678,create or replace table devsamelo2.dev_domesti...,DONE,41943040,76187,0,...,devsamelo2,dev_domestico,recebimento_geral_2022,None,None,None,None,None,manual,dev_domestico